name: Version Changes to the Main Branch

on:
  push:
    branches:
      - main

jobs:
  version-main-branch-changes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get last version number
      id: get_last_version
      run: |
        # Retrieve the last git tag, as we will only be processing one delivery line.
        last_version=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
        echo "Last version is $last_version"
        echo "last_version=$last_version" >> "$GITHUB_OUTPUT"

    - name: Get next version number
      id: get_next_version
      run: |
        # Retrieve the last git tag, as we will only be processing one delivery line.
        last_version=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
        echo "Last version is $last_version"
        # Split the version into its components
        a=( ${last_version//./ } )
        # If the last component is 9, then increment the middle component and reset the last component to 0
        if [[ ${a[2]} == 9 ]]; then
            next_version="${a[0]}.$((${a[1]}+1)).0"
        else
            # Otherwise increment the last component
            next_version="${a[0]}.${a[1]}.$((${a[2]}+1))"
        fi
        echo "Next version is $next_version"
        echo "next_version=$next_version" >> "$GITHUB_OUTPUT"

